query ServiceIntervalStatsQuery($services: [String], $startDate: String, $endDate: String) {
  serviceIntervalStats(services: $services, startDate: $startDate, endDate: $endDate) {
    service
    event
    occurrences
  }
}
